### ISSUE TITLE
Bar graph labels don't show cost

### ISSUE THREAD

**Issue by glynhudson** [tamslinn/AndroidApp#12]
In the old app when the 'cost' switch is toggled the labels on top of each bar of the daily bar graph changed to show the cost of each day:

## Power view (old app)

![screenshot_20170220-234725](https://cloud.githubusercontent.com/assets/758844/23145572/40a0c05c-f7c7-11e6-8f9b-11f8f1b02beb.png)

## Cost view (old app)

![screenshot_20170220-234729](https://cloud.githubusercontent.com/assets/758844/23145571/409eac4a-f7c7-11e6-8e7a-ba62eba86590.png)

***

In the beta app the bar graph labels always show the total Kwh even when the cost toggle is enabled:

## Power view (beta app)

![screenshot_20170220-235059](https://cloud.githubusercontent.com/assets/758844/23145603/77d68f5c-f7c7-11e6-8920-ff5eccf37d97.png)

## Cost view (beta app)

![screenshot_20170220-235103](https://cloud.githubusercontent.com/assets/758844/23145602/77d3cd30-f7c7-11e6-84f4-f1d076d171ed.png)

**Comment by tamslinn** [comment]
Oops missed this. It should be working as original now.
