### ISSUE TITLE
Feed name auto detect does not work immediately after adding new account

### ISSUE THREAD

**Issue by glynhudson** [tamslinn/AndroidApp#13]
https://www.youtube.com/watch?v=88TA5lpPUj0

I made a commit to tweak the feed title naming: https://github.com/emoncms/AndroidApp/commit/ba3a0e2b452d927806a8507302105fa2245dafd8

**Comment by tamslinn** [comment]
This works again now.

**Comment by glynhudson** [comment]
Yah! Works first time 👍
