### ISSUE TITLE
No way to select Wh bar graph feeds

### ISSUE THREAD

**Issue by glynhudson** [tamslinn/AndroidApp#14]
In the old app there was an option to use either kWh of wh bar graph feeds. This option seems to have been removed from the beta app.

This option is very useful for a lot of users who store their daily accumulating data in Wh rather than kWh. The beta app currently only supports kWh feeds, obviously, Wh feeds will work but the display will be an order of magnitude incorrect! 

Would it be possible to add this option back in? It's just a divided by 1000

Old app:
![screenshot_20170227-174109](https://cloud.githubusercontent.com/assets/758844/23373014/0550a86a-fd16-11e6-8e03-f9396e4c64c4.png)

**Comment by tamslinn** [comment]
I think I have fixed this. @glynhudson do you have a Wh feed to test it on? If I try it on my kWh feeds everything is 0 because the numbers are too small.

**Comment by tamslinn** [comment]
Tested, seems to be ok,
